### ISSUE TITLE
LCP terminated by peer, id=0x5

### ISSUE THREAD

**Issue by Amophis666** [ppp-project/ppp#83] opened 2017-05-18 05:45 UTC
I use a GPRS modem, and attach ISP called "TDC" in Denmark, 
then ppp server send back LCP TermReq. But HSPA modem works.
the log is as below:
================
SYSLOG 10: sent [LCP ConfReq id=0x1 <mru 1600> <asyncmap 0x0> <magic 0x326c4556>
 <pcomp> <accomp>]
ppp0 output: FF03C02101010018010406400206000000000506326C455607020802
SYSLOG 08: fsm_sdata(LCP): Sent code 1, id 1.
SYSLOG 10: Timeout 2dde10:c57f80 in 3 seconds.
SYSLOG 08: LCP: sending Configure-Request, id 1
ppp0 input: FF03C021010300190206000A00000702080205067377BDA10305C22305
SYSLOG 10: rcvd [LCP ConfReq id=0x3 <asyncmap 0xa0000> <pcomp> <accomp> <magic 0x7377bda1> <auth chap 05>]
[test----]LCP packet length:25 , total packet len:25
SYSLOG 08: fsm_rconfreq(LCP): Rcvd id 3.
SYSLOG 08: lcp_reqci: rcvd ASYNCMAP
SYSLOG 08: (a0000)
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd PCOMPRESSION
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd ACCOMPRESSION
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd MAGICNUMBER
SYSLOG 08: (7377bda1)
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd AUTHTYPE
SYSLOG 08: (c223)
SYSLOG 08:  (NAK)
SYSLOG 08: lcp_reqci: returning CONFNAK.
SYSLOG 10: sent [LCP ConfNak id=0x3 <auth pap>]
ppp0 output: FF03C021030300080304C023
SYSLOG 08: fsm_sdata(LCP): Sent code 3, id 3.
ppp0 input: FF03C021010500180206000A00000702080205067377BDA10304C023
SYSLOG 10: rcvd [LCP ConfReq id=0x5 <asyncmap 0xa0000> <pcomp> <accomp> <magic 0x7377bda1> <auth pap>]
LCP packet length:24 , total packet len:24
SYSLOG 08: fsm_rconfreq(LCP): Rcvd id 5.
SYSLOG 08: lcp_reqci: rcvd ASYNCMAP
SYSLOG 08: (a0000)
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd PCOMPRESSION
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd ACCOMPRESSION
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd MAGICNUMBER
SYSLOG 08: (7377bda1)
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: rcvd AUTHTYPE
SYSLOG 08: (c023)
SYSLOG 08:  (ACK)
SYSLOG 08: lcp_reqci: returning CONFACK.
SYSLOG 10: sent [LCP ConfAck id=0x5 <asyncmap 0xa0000> <pcomp> <accomp> <magic 0x7377bda1> <auth pap>]
ppp0 output: FF03C021020500180206000A00000702080205067377BDA10304C023
SYSLOG 08: fsm_sdata(LCP): Sent code 2, id 5.
SYSLOG 02: LCP: Retransmit the configure-request
[testtest-----]go->neg_mru(-1) && (go->mru(1600) != DEFMRU(1500))
SYSLOG 10: sent [LCP ConfReq id=0x1 <mru 1600> <asyncmap 0x0> <magic 0x326c4556> <pcomp> <accomp>]
ppp0 output: FF03C02101010018010406400206000000000506326C455607020802
SYSLOG 08: fsm_sdata(LCP): Sent code 1, id 1.
SYSLOG 10: Timeout 2dde10:c57f80 in 3 seconds.
SYSLOG 08: LCP: sending Configure-Request, id 1
ppp0 input: FF03C0210301000A0206000A0000
SYSLOG 10: rcvd [LCP ConfNak id=0x1 <asyncmap 0xa0000>]
LCP packet length:10 , total packet len:10
SYSLOG 08: fsm_rconfnakrej(LCP): Rcvd id 1.
SYSLOG 10: Untimeout 2dde10:c57f80.
go->neg_mru(-1) && (go->mru(1600) != DEFMRU(1500))
SYSLOG 10: sent [LCP ConfReq id=0x2 <mru 1600> <asyncmap 0xa0000> <magic 0x326c4556> <pcomp> <accomp>]
ppp0 output: FF03C02101020018010406400206000A00000506326C455607020802
SYSLOG 08: fsm_sdata(LCP): Sent code 1, id 2.
SYSLOG 10: Timeout 2dde10:c57f80 in 3 seconds.
SYSLOG 08: LCP: sending Configure-Request, id 2
ppp0 input: FF03C02102020018010406400206000A00000506326C455607020802
SYSLOG 10: rcvd [LCP ConfAck id=0x2 <mru 1600> <asyncmap 0xa0000> <magic 0x326c4556> <pcomp> <accomp>]
LCP packet length:24 , total packet len:24
SYSLOG 08: fsm_rconfack(LCP): Rcvd id 2.
SYSLOG 10: Untimeout 2dde10:c57f80.
SYSLOG 10: sent [LCP EchoReq id=0x0 magic=0x326c4556]
ppp0 output: FF03C02109000008326C4556
SYSLOG 08: fsm_sdata(LCP): Sent code 9, id 0.
SYSLOG 10: Timeout 2e1a24:c57f80 in 60 seconds.
SYSLOG 10: sent [PAP AuthReq id=0x1 user="amophis" password="1234"]
ppp0 output: FF03C023010100060000
SYSLOG 08: pap_sauth: Sent id 1.
SYSLOG 10: Timeout 2e1d8c:c57fc0 in 3 seconds.
ppp0 input:FF03C0210A0000087377BDA1
SYSLOG 10: rcvd [LCP EchoRep id=0x0 magic=0x7377bda1]
LCP packet length:8 , total packet len:8
ppp0 input:FF03C0230201000500
SYSLOG 10: rcvd [PAP AuthAck id=0x1 ""]
SYSLOG 08: pap_rauthack: Rcvd id 1.
SYSLOG 08: Remote message:
SYSLOG 10: sent [IPCP ConfReq id=0x1 <compress VJ 07 01> <addr 0.0.0.0> <ms-dns 0.0.0.0>]
ppp0 output: FF038021010100160206002D0701030600000000810600000000
SYSLOG 08: fsm_sdata(IPCP): Sent code 1, id 1.
SYSLOG 10: Timeout 2dde10:c506a0 in 3 seconds.
SYSLOG 08: IPCP: sending Configure-Request, id 1
ppp0: no compressor for [15 3 29], 3
ppp0: no compressor for [1a 4 8], 4
ppp0: no compressor for [18 4 8], 4
ppp0 input: FF03C02105050004
SYSLOG 10: rcvd [LCP TermReq id=0x5]
LCP packet length:4 , total packet len:4
SYSLOG 08: fsm_rtermreq(LCP): Rcvd id 5.
SYSLOG 08: LCP terminated by peer
SYSLOG 10: Untimeout 2e1a24:c57f80.
SYSLOG 10: Untimeout 2dde10:c506a0.
SYSLOG 10: Timeout 2dde10:c57f80 in 3 seconds.
SYSLOG 10: sent [LCP TermAck id=0x5]
ppp0 output: FF03C02106050004
ppp0 input: FF03C02105050004
SYSLOG 10: rcvd [LCP TermReq id=0x5]

**Comment by Amophis666** [comment] 2017-05-23 05:34
Is this issue related about timing of ppp packet transmission? I use this ppp package in different OS kernel, Linux works, but RTOS fail.

**Comment by Amophis666** [comment] 2017-05-23 05:40
After I check the RFC for LCP/CHAP/IPCP, the packet tx/rx log above is correct, now I focus on the timing of packet transmission in different OS kernel.

**Comment by nihilus** [comment] 2019-04-30 22:58
Which modem are you using?

**Comment by Neustradamus** [comment] 2021-01-01 06:00
@Amophis666: The problem is always here?

**Comment by Neustradamus** [comment] 2021-03-08 01:24
@Amophis666: The problem is always here?

**Comment by Neustradamus** [comment] 2022-10-25 18:34
@Amophis666: The problem is always here 5 years after?

**Comment by Neustradamus** [comment] 2024-08-17 14:10
@Amophis666: The problem is always here 7 years after?
Have you fixed with a recent version?
Details are important...

**Comment by Amophis666** [comment] 2024-08-17 18:04
Thanks for noticing the issue dude, I’ve given up as a software developer for a long time ><從我的iPhone傳送Neustradamus ***@***.***> 於 2024年8月17日 晚上10:11 寫道：﻿
@Amophis666: The problem is always here 7 years after?
Have you fixed with a recent version?
Details are important...

**Comment by paulusmack** [comment] 2024-08-21 09:48
Closing based on age and lack of sufficient detail.

**Closed by paulusmack** 2024-08-21 09:48 UTC
