### ISSUE TITLE
building ppp on musl with `<linux/ppp_defs.h>`

### ISSUE THREAD

**Issue by listout** [ppp-project/ppp#351] opened 2022-06-13 07:00 UTC
Hi, don't know if his is a right place to ask this. I'm Google Summer of Code student at gentoo porting stuff for musl libc. The ppp itself is compiles fine but packages like NetworkManager (and some other packages) fails to install with error such as `<net/ppp_defs.h> no such file or directory`. I'm trying to crate a patch specific to gentoo

I was trying to build ppp on musl with a patch that replaces `<net/ppp_defs.h>` to `<linux/ppp_defs>`

```diff
diff --git a/pppd/pppd.h b/pppd/pppd.h
index 88a1209..17cd8ed 100644
--- a/pppd/pppd.h
+++ b/pppd/pppd.h
@@ -57,7 +57,8 @@
 #include <sys/param.h>         /* for MAXPATHLEN and BSD4_4, if defined */
 #include <sys/types.h>         /* for u_int32_t, if defined */
 #include <sys/time.h>          /* for struct timeval */
-#include <net/ppp_defs.h>
+#include <linux/types.h>
+#include <linux/ppp_defs.h>
 #include "patchlevel.h"

 #ifdef INET6
```

When I try to compile it I get some errors saying `error: 'PPP_EAP' undeclared (first use in this function); did you mean 'PPP_ECP'?` Any advice on how to get around this error would be helpful.

Saw a similar discussion on pull request #293, unfortunately that pull request was not merged. I tried implementing the idea @enaess suggested in comments got the same error.

**Comment by paulusmack** [comment] 2022-07-04 00:07
It seems to me that the problem is entirely between NetworkManager and musl libc. Do you know what definitions NetworkManager needs that it is looking for in ppp_defs.h?

We can't put #include <linux/...> in pppd.h, at least not without an #ifdef, because pppd supports Solaris as well as Linux.

The error you get is (I presume) because the include/linux/ppp_defs.h in the pppd sources is essentially unused and is now out of date.

**Comment by enaess** [comment] 2022-07-04 00:32
The more reasons to eliminate it from the PPP sources when compiled on Linux. Seems like there is a compile issue when using a stale version with glibc (and not present in musl). 

Hope this become more clear when you review my change

**Comment by listout** [comment] 2022-07-04 05:25
@paulusmack, @enaess For some reason, I can't reproduce the issue with the latest update of musl and NetworkManager. Maybe someone updated or patched NetworkManager

**Comment by paulusmack** [comment] 2022-07-09 10:25
In that case I'll close this issue; reopen it (or create a new one) if/when you can reproduce it.

**Closed by paulusmack** 2022-07-09 10:25 UTC
